version: "2"
services:
  backend1:
    build: ./server1
    ports:
      - "8080"
  backend2:
    build: ./server2
    ports:
      - "8081"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
