# Use an official Node.js Alpine image as a parent image
FROM node:18.16.1-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the app, when you will run a container from the image build using this dockerfile
CMD ["node", "server.js"]